package com.ericsson.msc.group5.dao;

import java.util.Collection;
import com.ericsson.msc.group5.entities.FailureTrace;

/**
 * A Data Access Object interface for the FailureTrace entity. Defines common
 * DAO methods.
 */
public interface FailureTraceDAO {

	public Collection <FailureTrace> getEventCauseForImsi(String imsi);

	/**
	 * Retrieve all FailureTrace objects present in the data store.
	 * 
	 * @return a Collection of FailureTrace objects; empty collection if no
	 *         FailureTrace objects are present in the data store.
	 */
	public Collection <FailureTrace> getAllFailureTraces();

	/**
	 * Insert a new FailureTrace object into the data store.
	 * 
	 * @param failureTrace
	 *            A new FailureTrace object.
	 */
	public void insertFailureTrace(FailureTrace failureTrace);

	/**
	 * Update a FailureTrace object that exists in the data store. Object
	 * comparison is based on the unique autogenerated failureTraceId.
	 * 
	 * @param failureTrace
	 *            A FailureTrace entity that exists in the data store. An
	 *            exception will be thrown the provided FailureTrace is not in
	 *            the data store.
	 */
	public void updateFailureTrace(FailureTrace failureTrace);

	/**
	 * Delete an existing FailureTrace object from the data store. Object
	 * comparison is based on the unique autogenerated failureTraceId.
	 * 
	 * @param failureTrace
	 *            A FailureTrace entity that exists in the data store. An
	 *            exception will be thrown the provided FailureTrace is not in
	 *            the data store.
	 */
	public void deleteFailureTrace(FailureTrace failureTrace);

	/**
	 * Batch insert a Collection of FailureTrace objects into the data store.
	 * Optimized for handling large volumes of data.
	 * 
	 * @param failureTraceList
	 *            A collection of new FailureTrace objects.
	 */
	public void batchInsertFailureTrace(
			Collection <FailureTrace> failureTraceList);
}
