package com.ericsson.msc.group5.dao;

import java.util.List;
import com.ericsson.msc.group5.entities.FailureTrace;

/**
 * A Data Access Object interface for the FailureTrace entity. Defines common DAO methods.
 */
public interface FailureTraceDAO {

	/**
	 * Retrieve all FailureTrace objects present in the data store.
	 * 
	 * @return a List of FailureTrace objects; empty list if no FailureTrace objects are present in the data store.
	 */
	public List <FailureTrace> getAllFailureTraces();

	/**
	 * Insert a new FailureTrace object into the data store.
	 * 
	 * @param failureTrace
	 *            A new FailureTrace object.
	 */
	public void insertFailureTrace(FailureTrace failureTrace);

	/**
	 * Update a FailureTrace object that exists in the data store. Object comparison is based on the unique autogenerated failureTraceId.
	 * 
	 * @param failureTrace
	 *            A FailureTrace entity that exists in the data store. An exception will be thrown the provided FailureTrace is not in the data store.
	 */
	public void updateFailureTrace(FailureTrace failureTrace);

	/**
	 * Delete an existing FailureTrace object from the data store. Object comparison is based on the unique autogenerated failureTraceId.
	 * 
	 * @param failureTrace
	 *            A FailureTrace entity that exists in the data store. An exception will be thrown the provided FailureTrace is not in the data store.
	 */
	public void deleteFailureTrace(FailureTrace failureTrace);

	/**
	 * Batch insert a list of FailureTrace objects into the data store. Optimized for handling large volumes of data.
	 * 
	 * @param failureTraceList
	 *            A list of new FailureTrace objects.
	 */
	public void batchInsertFailureTrace(List <FailureTrace> failureTraceList);
}
